### ISSUE TITLE
Simplify language files

### ISSUE THREAD

**Issue by psypanda** [DakJaniels/LuiExtended#104]
Since the number of strings in the language files is increasing rapidly we should take a closer look on redundant lines not necessary for translation.

**Example:**
> SI_LUIE_SKILL_GENERIC_BLEED_0_2_SEC_TP = "Afflicted with Bleeding Damage every |cFFFFFF0.2|r seconds for |cFFFFFF<<1>>|r <<1[second/seconds]>>.",
>SI_LUIE_SKILL_GENERIC_BLEED_0_5_SEC_TP = "Afflicted with Bleeding Damage every |cFFFFFF0.5|r seconds for |cFFFFFF<<1>>|r <<1[second/seconds]>>.",

**TODO:**
- [x] `en.lua`
- [x] `ru.lua`
- [x] `Settings_en.lua`
- [x] `Settings_ru.lua`
- [x] `Skills_en.lua`
- [x] `Skills_ru.lua`

This will make future translation to other languages (`fr` `de` `jp`) much easier.
Also some strings use `\"something\"` and some use `'something'`. We'd probably change those to use single quotes so no escape chars are needed.
