### ISSUE TITLE
CombatInfo - Alerts Rework - CHECKLIST

### ISSUE THREAD

**Issue by ArtOfShred** [DakJaniels/LuiExtended#111]
-- Localization
- [x] Localization

-- Options
- [x] Fix some variable names to be more consistent
- [x] Display Duration Label Y/N
- [x] Duration Label Color
- [x] Display CC Type Color Border Y/N
- [x] Incoming Alerts - add option to hide alerts if CC type is not (BLOCK, DODGE, FEAR, DISORIENT, STAGGER, SNARE/IMMOBILIZE, or no CC)
- [x] Play Sound Priority 1/2/3 Y/N
- [x] Fix "HIDE MITIGATION SUGGESTIONS" option to instead be a "Display Mitigation Suggestions" toggled on by default.

-- Frame
- [x] Make sure resize when font changes are made
- [x] Icon used font size as base or add icon size option?

-- Sounds
- [x] Add more LAM sounds
- [x] Change the sounds selected for current
- [x] Make sure default options are alright (sound for all boss alerts, only CC for lower maybe?)
- [x] Make sure all sound conditionals work correctly

-- Interrupts?
- [x] Add a handler for when enemies are interrupted/stunned/killed/etc (do as much as I can at least)
- [x] Use fade func from SCB to popup "INTERRUPTED" that fades out or something
- [x] Possibly add .5 or 1 sec fade animation to alerts? - but set available = true so new ones can override during the fade animation?

**Comment by ArtOfShred** [comment]
I AM COMPLETEEEEEEEEEEEEEEEE
