### ISSUE TITLE
Icon & Aura Update Checklist

### ISSUE THREAD

**Issue by ArtOfShred** [DakJaniels/LuiExtended#147]
This list serves to track icons that need updated to the new quality standard.
* [ ] Transfer everything from paper onto this list then delete this checkbox.

**Player Abilities:**
* [ ] Nightblade - Shade - Corrode (Melee)
* [ ] Nightblade - Shade - Corrode (Whirlwind)
* [ ] Nightblade - Shade - Corrode (Ranged)
* [ ] Warden - Bear - Bite (*depends on Bear*)
* [ ] Warden - Bear - Crushing Swipe (*depends on Bear*)
* [ ] Necromancer - Mage - Deathbolt
* [ ] Necromancer - Archer - Deathbolt
* [ ] Necromancer - Spirit (*double check I don't think this has/needs a custom icon*)
* [ ] Undaunted - Spider Melee (*depends on Giant Spider*)
* [ ] Undaunted - Spider Poison Spit
* [ ] Update Racial Icon backdrops

**Generic Warrior/Rogue/Mage/Healer/Templar/etc icons/:**
* [ ] rogue_053 = Allene Pellingare - Ghost Burst (jump radial AOE w/ Dawnbreaker sound)
* [ ] rogue_038 = Yalorasse - Shadowstep Backstab - should be same effects as ambush, replace.
* [ ] warrior_004 = Tidal Slash + Leap Attacks
* [ ] warrior_010 = TAUNT
* [ ] warrior_011 = Shield Rush - maybe just leave this alone
* [ ] warrior_014 = Retaliation
* [ ] warrior_020 = IDK what to do with this
* [ ] warrior_031 = Akash gra-Mal - Battlecry (replace with custom backdrop icon or another yell)
* [ ] warrior_032 = Divine Leap
* [ ] Shard Shield - needs a completely different style of icon
* [ ] ability_templar_blessing - Gathwen - Quest Heal - replace
* [ ] Impulse Mine = vvardenfel_048
++ ADD HEALER/MAGE ICONS HERE ++

**NPC Abilities:**
* [ ] Guard - "Mighty Charge" (*maybe a new icon or name or something for this guard version of critical charge*)
* [ ] Winterborn Warrior - Retaliation
* [ ] Justice Civilian - Stab
* [ ] Peasant Weapon Attacks
* [ ] Harpy - Charged Ground
* [ ] Wisp - Assault
* [ ] Wisp - Dying Blast
* [ ] World Boss - Shadow Flare (Reflective Shadows detonation)
* [ ] Dreadweaver - Absorb Magic - new icon, maybe new name?
* [ ] Frost Mage - Barrier + Chill + Winter's Reach
* [ ] Ice Wraith - Blood in the Water

**Traps:**
* [ ] Flame Jet

**Quests Ablities:**
* [ ] MG - Summon Scamp
* [ ] MG - Summon Pig
* [ ] MSQ - Royal Strike
* [ ] MSQ - Gravity Well (use HOSE icon + Angelina buff icon combo to make this)
* [ ] Vvardenfell - Ash Storm

**Dungeons:**
* [ ] Wayrest II - Shield Sibling
* [ ] Wayrest II - Necrotic Arrow
* [ ] Wayrest II - Pellingare Prison
* [ ] Wayrest II - Malubeth Projectile
* [ ] VMA - Frost Breath

**Ability Behavior Checklist:**
* [ ] Add id's for hiding spot to Miat's blacklist or use get AbilityName for one of the id's to localize and blacklist it (TODO 1B).
