### ISSUE TITLE
Module Update Checklist (General, CA, CI, CT, IP, SCB, UF)

### ISSUE THREAD

**Issue by ArtOfShred** [DakJaniels/LuiExtended#148]
List of updates/changes to add for various components:

**General:**
* [x] Binding for Leave Group
* [x] Binding for /reloadui
* [ ] After finished processing all Alert/CSA (add any additional XP Bar popups here if present)
* [ ] The LAM settings menu for `SlashCommands > General Commands` contains some left over Temp Settings. Clean these up one appropriate Chat Announcements settings are added.
* [x] Look into issue where Keybind summons for banker/merchant aren't displaying by default with CA option disabled (slash commands/keybinds should always display a chat output response)
* [x] Hook Skills Advisor for Gamepad mode to fix issues with icon inconsistency.
* [ ] Maybe - Potentially add some type of Activity Finder tracking features like BUI (requested).

**Buffs & Debuffs:**
* [ ] Add a whitelist and container for tracking prominent debuffs on the player (I.E. Power of the Light / Haunting Curse / etc is applied on you).
* [ ] Standard implementation (buff container with bars) or use a different format? Almost considering a longer bar sort of like Dark Souls status effects (with a timer and icon still) to stand out more prominently.
* [ ] MAYBE - Customize icon size for Prominent Containers.
* [ ] Optimize sorting function if possible - need to look and see how much room for improvement exists. There's some minor oddities with the sorting function still too.

**Chat Announcements:**
* [ ] Group Kick - You can kick yourself from the group (lol maybe I can add a check for this but it's kinda funny you can do this).
* [x] Group Kick - Events seem to fire in different order sometimes when the group consists of only 2 players and the leader kicks the remaining other player. Sometimes it shows as isLeader and isLocalPlayer event first and other times the other group member. Might be some way to normalize this so it always shows as a disband when kicking the player, or always shows as a kick, or maybe a special message like "You have kicked [x], disbanding the group."
* [x] Group Leave - Same issue as above with just a 2 player group, sometimes when the other player leaves it shows them leaving, other times shows as you leaving depending on the order events fire in.
* [x] Game Issue - EVENT_GROUP_MEMBER_JOINED not working properly, not much can be done for now but keep an eye on this. May have to fix/alter IndexGroupLoot function to compensate for this, possibly shifting it over to EVENT_GROUP_UPDATE.
* [ ] CA for Outfits
* [ ] *MAYBE* - CA for antiquity fragments (pieces of Ring of the Wild Hunt, etc)
* [ ] Transmute CA - "[Item Name] changed to TRAIT"
* [x] Change some Guild Announcements settings (toggle management off by default I think so Rank - actual rank name - updates don't show)
* [x] Display Announcement - DSA Waves / Craglorn Quests / maybe figure out some better way to handle these or stop handling most because there are way too many to address.
* [ ] Bristleneck Boar - add a CA of some sort for the bag space increase?
* [ ] Quest Log - skip “Filled: TRACKER GOAL TEXT”
* [x] No event showing for Respec (check EVENT_ATTRIBUTE_FORCE_RESPEC & EVENT_SKILL_FORCE_RESPEC)
* [x] Respec - check if actual ingame respec events show a message (since scroll does not) / check consistency with these + champion respec
* [ ] Instance Boot warning - ZO_InstanceKickWarning:OnInstanceKickTimeUpdate() displays an alert in the corner when you leave a dungeon group and get ported. Can add this to group handlers. (Seems local, might have to SafeAddString and forgo having a CA option)
* [ ] Guild Roster: Applicant Received
* [ ] Guild Roster: Blacklist Updated
* [ ] Guild Roster: Pending Invite
* [ ] Guild Roster: You apply to Guild
* [ ] Guild Roster: Your app to guild is denied
* [ ] Guild Roster: Application Updated
* [ ] Guild Roster: You decline/accept an application
* [ ] Guild: Add error message for "already invited to roster" to match "already in guild" error.
* [ ] Can we show guild logon/logoff messages or is it going to be performance intensive.
* [ ] PLAYER TO PLAYER MENU: Examine functionality differences between ignored player feedback for Duel/Invite/Whisper/Group, maybe adjust for normalization.
* [x] EVENT_GROUP_INVITE_RESPONSE - Does this properly have a response for CONSIDERING_ANOTHER error?
* [ ] Messages (Alert) for - when Stealth Suppresion is on - Can't Pickup Scroll - Missing Scrolls -
* [ ] Add Wrothgar Trophy Messages
* [ ] Maybe toggle for "Resuming fight in Progress" from Dungeons too?
* [ ] Make sure Heraldry function actually works.
* [ ] Look into adding Dyes + Titles to achievement announcements.
* [ ] Many new messages can be added:
    * Porting to Wayshrine
    * No Permissions for Guild Bank modifications
    * LFG Jump Notes
    * Cyrodiil Campaign Queue
    * PVP Guild Keep Claim (Maybe)
    * Purchase Messages from AH (probably not needed)
    * Repair Messages in LUI syntax
    * Bounty Paid/Edict Used
    * Fishing
    * Ress Alert
    * Recipes/Motifs learned? (Motifs show under lorebooks currently)
    * Justice Update CSA

**Combat Info:**
* [ ] Cast Bar - Add Cast Bar Tick Rate Slider
* [ ] Bar Highlight - Adjust or require reload on Bar Highlight Changes (error prevention)
* [ ] Bar Highlight - Add colored Radial Border to back bar (option to use on front bar too)
* [ ] Bar Highlight - Option to displace Default Frames up when a backbar ability is active and return to normal position if nothing is displayed.
* [ ] Ultimate Label - Make the percentage cap optional so it continues to show above 100% ultimate value.
* [ ] MAYBE add a Hook for AlphaGear / other gear addons to call the backbar icons to update.
* [ ] Add option to not swap bar positions when both ability bars are shown (Ultimate swaps up/down? Shows for both?)

**Combat Text:**
* [ ] Add alert for stealth broken / stealth suppression.
* [ ] Fix all methods to scroll up properly as well
* [ ] Make scroll speed not require ReloadUI
* [ ] Add an option to switch the position of spell name positions for combat messages.
* [ ] Add the option to display the ability / buff border on combat text icons.

**Info Panel:**
* [ ] BUG -When disabling FPS, Latency, and Clock - the Soul Shards counter moves into the second row and overlaps with the leftmost object.

**Slash Commands:**
* [x] Add an option for /eye for Antiquities.
* [ ] /disband command, could add the same confirmation dialogue present in the group menu when using this command.

**Unit Frames:**
* [ ] Possibly - Preview Unit Frame Configuration Appearance with mocked up bars
* [ ] Add a customizable option to alter the throttle time on XP bar update for Champion Points (or try to simplify function so its not necessary to throttle)
* [x] Sort Unit Frames in order of TANK > HEALER > DPS (for GROUP FRAMES)
* [ ] Sort Offline Frames LAST
* [ ] Default UI Buffs + Debuffs don't show if default target frame is hidden. Need a way around this. EDIT: Not sure there is any to display this with the target frame hidden. Might revisit later.
* [ ] Add numeric value onto separate shield bar
* [ ] Add option to remove class/guild/friend/ignore icons off bars
* [ ] Allow execute skull to be moved.
* [ ] Compact mode for Group Unit Frames
* [ ] Add Boss Phase tick marks option
* [ ] Add icon for Race to Player/Target
* [ ] Add icon for Alliance to Player/Target

**Future:**
* [ ] Chat Announcements - Update Groupfinder votekick function to display more information when you are the player initiating a kick (if they ever fix the API for GetGroupElectionInfo()
