### ISSUE TITLE
Buffs & Debuffs Update Checklist

### ISSUE THREAD

**Issue by ArtOfShred** [DakJaniels/LuiExtended#179]
**Add additional color options for Buff & Debuff frames:**
* [x] Fake Buffs (Charging Maneuvers, Recall Penalty) can't be prominent. Add support.
* [x] Priority Buffs Whitelist - Add a buff to a priority whitelist to highlight the frame in a different color (Debuff support too?)
* [x] Color Frame by CC Type & Color Options for CC Types (this will take a long time to fully implement since it requires table data)
* [x] Add an option to use generic CC icons for hard cc/soft cc with a "also player abilities" modifier. To make cc easier to determine. (Requires table data that also supports the issue above)
* [x] Add color option for Unbreakable Debuffs
* [x] Add color option for Theater Buffs (Memento's, etc)

**Alignment Options / Format Options:**
* [x] Add Horizontal / Vertical Alignment Methods independently for each container for more control.
* [x] Update Horizontal/Vertical direction change to NOT require a /reloadUI

**Tooltips:**
* [x] Ground Effects - change the type displayed in detailed tooltips.

**Misc:**
* [x] Remove the separate "Long Term Effects" submenu and move those options into filters.
* [x] Add an option in Short Term Effects Filters to hide all short term effects.

**Bug Fixes & Tweaks:**
* [x] Consolidate menus a bit - Ideally we want a submenu for Priority Buffs, Prominent Buffs (Player) and Prominent Debuffs (Incoming) so we want to try to lower the number of menus outside of that.
